force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/NVMStatsSF__NVM_Call_Summary__c.object-meta.xml
<CustomObject>
    <label>Vonage Call Summary</label>
    <nameField>
        <displayFormat>NVMCS-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vonage Call Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__CallTime__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__CallTime__c</fullName>
    <inlineHelpText>Date/Time stamp of Call Start (stored internally as UTC but shown in Salesforce to you in your timezone)</inlineHelpText>
    <label>CallTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__Interaction_Type__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__Interaction_Type__c</fullName>
    <inlineHelpText>The Call or Case type, e.g. Inbound/Outbound/Case</inlineHelpText>
    <label>Interaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Automated Outbound Call</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Internal Call</fullName>
            </value>
            <value>
                <fullName>Phone Callback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Service_Name_Practice__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_Practice__c</fullName>
    <formula>IF (CONTAINS(NVMStatsSF__NVM_Service_Name__c,&quot;West St Paul&quot;),&quot;West St Paul&quot;,
IF (CONTAINS(NVMStatsSF__NVM_Service_Name__c,&quot;HattiesburgMS ACI Internet&quot;),&quot;Hattiesburg&quot;,
IF (LEN(MID(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c),
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1) - FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)
    )) = 3 , LEFT(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)
    ), IF (LEN(MID(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1),
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1) - FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)
    )) = 3 , LEFT(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)
)  , 
    
    IF (LEN(
        MID(NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1),
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1)+1) - FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1))
    ) = 3 , LEFT(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1)
), NVMStatsSF__NVM_Service_Name__c)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Name Practice</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Service_Practice_Match__c.field-meta.xml
<CustomField>
    <fullName>Service_Practice_Match__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Practice Match?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CallSummaryJob.cls
public class CallSummaryJob {
    
    public static DateTime startdate = DateTime.newInstance(Date.today()-1, Time.newInstance(0,0,0,0)); 
    public static DateTime enddate = DateTime.newInstance(Date.today(), Time.newInstance(0,0,0,0)); 
    public static List<NVMStatsSF__NVM_Call_Summary__c>lstScheduled = new List<NVMStatsSF__NVM_Call_Summary__c>(); 
    
    @future
    public static void run() {  	
        updatePracticeMatch();
    }
    
    public static void updatePracticeMatch() {   
        //Debugging
        System.debug('Start Date:'+ startdate);
        System.debug('End Date:'+ enddate);

        //calls scheduled or re-scheduled
        lstScheduled = [SELECT Id, NVMStatsSF__CallTime__c, Service_Name_Practice__c, 
                        NVMStatsSF__Related_To__c,NVMStatsSF__CallDisposition__c,Service_Practice_Match__c
                        FROM NVMStatsSF__NVM_Call_Summary__c 
                        WHERE NVMStatsSF__Interaction_Type__c = 'Inbound Call'
                        AND NVMStatsSF__CallTime__c >=: startdate
                        AND NVMStatsSF__CallTime__c <: enddate
                        AND Service_Name_Practice__c !=: '800 DENTURES'
                        AND (NVMStatsSF__CallDisposition__c =: 'Scheduled' OR
                             NVMStatsSF__CallDisposition__c =: 'Rescheduled')
                        ORDER BY NVMStatsSF__CallTime__c DESC ];
        //Debugging
        System.debug('Records Retrieved: '+ lstScheduled.size());
        
        for(NVMStatsSF__NVM_Call_Summary__c call:lstScheduled) {
            if(call.NVMStatsSF__Related_To__c!=null) {
                 
                if(call.NVMStatsSF__Related_To__c.replace('.','').tolowercase().indexOf(call.Service_Name_Practice__c.replace('N ','North ').replace('E ','East ').tolowercase()) != -1) {
                    call.Service_Practice_Match__c = true;
                }
                
                if(call.NVMStatsSF__Related_To__c == 'Phoenix - Arizona' && 
                   call.Service_Name_Practice__c == 'Phoenix Sun City' ) {
                       call.Service_Practice_Match__c = true;
                   }
                
            }
        }
        
        Database.SaveResult[] sr = Database.update(lstScheduled,false); 
        System.debug('Save Result');
        system.debug(sr);
        
    } 
    
    
}