force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/NVMStatsSF__NVM_Call_Summary__c.object-meta.xml
<CustomObject>
    <label>Vonage Call Summary</label>
    <nameField>
        <displayFormat>NVMCS-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vonage Call Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__CallTime__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__CallTime__c</fullName>
    <inlineHelpText>Date/Time stamp of Call Start (stored internally as UTC but shown in Salesforce to you in your timezone)</inlineHelpText>
    <label>CallTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__CLID__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__CLID__c</fullName>
    <inlineHelpText>The number presented by Caller (Caller ID)</inlineHelpText>
    <label>CLID</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__EndRecorded__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__EndRecorded__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked if the Call End Event was received from ContactWorld; indicative of completeness of a Call Summary. The End Event for Inbound Calls and Cases conveys the total duration; if missing, duration is approximated using sub totals known.</inlineHelpText>
    <label>EndRecorded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__Interaction_Type__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__Interaction_Type__c</fullName>
    <inlineHelpText>The Call or Case type, e.g. Inbound/Outbound/Case</inlineHelpText>
    <label>Interaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Automated Outbound Call</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Internal Call</fullName>
            </value>
            <value>
                <fullName>Phone Callback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__NVM_Service_Name__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__NVM_Service_Name__c</fullName>
    <inlineHelpText>The service/line name that was called</inlineHelpText>
    <label>Service Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Contact this call relates to (as indicated by a Task record whose CallObject matches the GUID from this summary)</inlineHelpText>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>NVM_Call_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Service_Name_Practice__c.field-meta.xml
<CustomField>
    <fullName>Service_Name_Practice__c</fullName>
    <formula>IF (CONTAINS(NVMStatsSF__NVM_Service_Name__c,&quot;West St Paul&quot;),&quot;West St Paul&quot;,
IF (CONTAINS(NVMStatsSF__NVM_Service_Name__c,&quot;HattiesburgMS ACI Internet&quot;),&quot;Hattiesburg&quot;,
IF (LEN(MID(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c),
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1) - FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)
    )) = 3 , LEFT(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)
    ), IF (LEN(MID(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1),
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1) - FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)
    )) = 3 , LEFT(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)
)  , 
    
    IF (LEN(
        MID(NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1),
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1)+1) - FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
        FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1))
    ) = 3 , LEFT(
    NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c,
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c, 
    FIND(&quot; &quot;, NVMStatsSF__NVM_Service_Name__c)+1)+1)
), NVMStatsSF__NVM_Service_Name__c)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Name Practice</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Service_Practice_Match__c.field-meta.xml
<CustomField>
    <fullName>Service_Practice_Match__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Practice Match?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CallSummaryJobTest.cls
@isTest
public class CallSummaryJobTest {
 static testMethod void test_Job() {
      NVMStatsSF__NVM_Call_Summary__c call1 = new NVMStatsSF__NVM_Call_Summary__c();
        NVMStatsSF__NVM_Call_Summary__c call2 = new NVMStatsSF__NVM_Call_Summary__c();  
        
      //test data for fees/services call > new tracking object
        Id RecordTypeIdAcct = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Schedule Assist').getRecordTypeId();
        Account a = new Account(name='Asheville - NC', recordtypeid=RecordTypeIdAcct);
        insert a;
        
        Contact c = new Contact(firstname='John',lastname='Doe',email='jdoe@example.com');
        c.accountid = a.id;
        insert c; 
     
        call1 = new NVMStatsSF__NVM_Call_Summary__c();
        call1.NVMStatsSF__CLID__c = '9198005551212';
        call1.NVMStatsSF__NVM_Service_Name__c = 'Asheville';
        call1.NVMStatsSF__Related_Contact__c = c.id;
        call1.NVMStatsSF__EndRecorded__c = true; 
        call1.NVMStatsSF__CallDisposition__c = 'Scheduled';
        call1.NVMStatsSF__CallTime__c = DateTime.newInstance(Date.today() -1,time.newInstance(11,0,0,0));
        call1.NVMStatsSF__Interaction_Type__c = 'Inbound Call';
        call1.NVMStatsSF__Agent_Talk_Time__c = 0;
        insert call1;
       

        system.debug(call1);  
     system.test.startTest();
     CallSummaryJob.run();
     system.test.stopTest();
     
         call1 =   [SELECT Id, NVMStatsSF__CallTime__c, Service_Name_Practice__c, 
                   NVMStatsSF__Related_To__c,NVMStatsSF__CallDisposition__c,Service_Practice_Match__c
                        FROM NVMStatsSF__NVM_Call_Summary__c 
                           WHERE Id =: call1.id ];
     system.debug(call1);
     system.assertEquals(1,CallSummaryJob.lstScheduled.size());
     system.assertequals(true,call1.Service_Practice_Match__c);
}
}