force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/NVMStatsSF__NVM_Call_Summary__c.object-meta.xml
<CustomObject>
    <label>Vonage Call Summary</label>
    <nameField>
        <displayFormat>NVMCS-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vonage Call Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Call_Result_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Call_Result_Subcategory__c</fullName>
    <description>Call Result Subcategory value copied from the Call Task if one was found</description>
    <inlineHelpText>Call Result Subcategory value copied from the Call Task if one was found</inlineHelpText>
    <label>Call Result Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Denture</fullName>
                <label>New Denture (Patient is new to wearing dentures)</label>
            </value>
            <value>
                <fullName>Replacement Denture</fullName>
                <label>Replacement Denture (Patient is a current denture wearer)</label>
            </value>
            <value>
                <fullName>Partial Denture</fullName>
            </value>
            <value>
                <fullName>Implant Supported Denture</fullName>
            </value>
            <value>
                <fullName>All-In-One</fullName>
            </value>
            <value>
                <fullName>Single Tooth Implant</fullName>
            </value>
            <value>
                <fullName>Extraction Only</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Conversation Analyzer Category</description>
    <label>Insurance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Insurance_Plan__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Plan__c</fullName>
    <label>Insurance Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>Ameritas</fullName>
            </value>
            <value>
                <fullName>Blue Cross Blue Shield</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Delta Dental</fullName>
            </value>
            <value>
                <fullName>DentaQuest</fullName>
            </value>
            <value>
                <fullName>Dentemax</fullName>
            </value>
            <value>
                <fullName>GEHA</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Medicaid</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Aetna</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Cigna</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Humana</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - other</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - United Concordia</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - United Healthcare</fullName>
            </value>
            <value>
                <fullName>MetLife</fullName>
            </value>
            <value>
                <fullName>Other Commercial Insurance</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>United Concordia</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Reason_for_Not_Scheduling__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Not_Scheduling__c</fullName>
    <label>Reason for Not Scheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COVID</fullName>
            </value>
            <value>
                <fullName>Date of first available appointment is too far out</fullName>
            </value>
            <value>
                <fullName>Need to arrange transportation</fullName>
            </value>
            <value>
                <fullName>Need to talk to spouse/patient</fullName>
            </value>
            <value>
                <fullName>Practice doesn&apos;t take caller&apos;s insurance</fullName>
            </value>
            <value>
                <fullName>Price shopping</fullName>
            </value>
            <value>
                <fullName>Saving up money/waiting for tax return</fullName>
            </value>
            <value>
                <fullName>Service not offered</fullName>
            </value>
            <value>
                <fullName>Service too expensive</fullName>
            </value>
            <value>
                <fullName>Other [please add note]</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CallSummaryUpdate.cls
global class CallSummaryUpdate implements Database.Batchable<sObject>, Database.Stateful {
    
    global Set<id> tskids;         
    global Map<Id,Task> tskList;
    global List<Sobject> lstSObject;
    global String tskSubcategory;
    global String tskReasonForNotScheduling;
    global String tskInsurance;
    
    global CallSummaryUpdate(List<Sobject> lstObj){
        lstSObject = lstObj;   
    }
    
    global Iterable<Sobject> start(Database.BatchableContext bc){        
        return lstSObject;
    }
    
    global void execute(Database.BatchableContext bc, List<Sobject> lstObj){
        tskids = new Set<Id>();
        List<NVMStatsSF__NVM_Call_Summary__c> lstCS = new List<NVMStatsSF__NVM_Call_Summary__c>();
        NVMStatsSF__NVM_Call_Summary__c cs = new NVMStatsSF__NVM_Call_Summary__c();
        for(Sobject so: lstObj) {
            cs = (NVMStatsSF__NVM_Call_Summary__c)so;
            lstCS.add(cs);
        }
        retrieveTaskIdsFromCallSumary(lstCS);
        retrieveSubcategoryFromRelatedTasks();
        assignTaskSubcategoryToCallSummaryList(lstCS);
        updateCallSummaryList(lstCS);        
    }
    
    global void retrieveTaskIdsFromCallSumary(List<NVMStatsSF__NVM_Call_Summary__c> nvm_summary){
         for(NVMStatsSF__NVM_Call_Summary__c nvm : nvm_summary){    
            tskids.add(nvm.NVMStatsSF__TaskID__c);
            System.debug('Task Id ' + nvm.NVMStatsSF__TaskID__c);
        }
    }
    
    global void retrieveSubcategoryFromRelatedTasks(){        
        tskList = new Map<Id,Task>();
        if(tskids.size() > 0){            
            for(Task t: [Select id,Answered_Outcome__c, Reason_for_Not_Scheduling__c, Insurance__c from Task where id in :tskids  ALL ROWS]){
                tskList.put(t.id,t);
            }
        }        
    }
    global void assignTaskSubcategoryToCallSummaryList(List<NVMStatsSF__NVM_Call_Summary__c> nvm_summary){        
        if(tskList.size() > 0){
            for(NVMStatsSF__NVM_Call_Summary__c nvm : nvm_summary){               
                if(tskList.get(nvm.NVMStatsSF__TaskID__c) != null){
                    
                    tskSubcategory = tskList.get(nvm.NVMStatsSF__TaskID__c).Answered_Outcome__c;
                    tskReasonForNotScheduling = tskList.get(nvm.NVMStatsSF__TaskID__c).Reason_for_Not_Scheduling__c;
                    tskInsurance = tskList.get(nvm.NVMStatsSF__TaskID__c).Insurance__c;
                    
                    if(tskSubcategory != null && nvm.Call_Result_Subcategory__c != tskSubcategory){
                        nvm.Call_Result_Subcategory__c = tskSubcategory;
                        System.debug('Subcategory ' + nvm.Call_Result_Subcategory__c);
                    }
                    
                    if(tskReasonForNotScheduling != null && nvm.Reason_for_Not_Scheduling__c != tskReasonForNotScheduling){
                        nvm.Reason_for_Not_Scheduling__c = tskReasonForNotScheduling;
                        System.debug('Reason for not scheduling' + nvm.Reason_for_Not_Scheduling__c);
                    }
                    
                    if(tskInsurance != null && nvm.Insurance_Plan__c != tskInsurance){
                        nvm.Insurance_Plan__c = tskInsurance;
                        System.debug('Insurance ' + nvm.Insurance_Plan__c);
                    }
                } 
            }
        }        
    }
    
    global void updateCallSummaryList(List<NVMStatsSF__NVM_Call_Summary__c> nvm_summary){
        try{
            Database.SaveResult[] results = Database.update(nvm_summary,false);              
            for(Database.SaveResult result: results){
                if(!result.isSuccess()){
                    for(Database.Error error: result.getErrors()){
                        System.debug('Error Status: ' + error.getStatusCode() +': Error fields: ' + error.getFields());
                    }
                }
            }
        }
        catch(Exception e){
            System.debug('Exception: ' + e.getMessage());
        }
    }
    
    global void finish(Database.BatchableContext bc){
        
    }
    
}