force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/NVMStatsSF__NVM_Call_Summary__c.object-meta.xml
<CustomObject>
    <label>Vonage Call Summary</label>
    <nameField>
        <displayFormat>NVMCS-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vonage Call Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Call_Result_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Call_Result_Subcategory__c</fullName>
    <description>Call Result Subcategory value copied from the Call Task if one was found</description>
    <inlineHelpText>Call Result Subcategory value copied from the Call Task if one was found</inlineHelpText>
    <label>Call Result Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Denture</fullName>
                <label>New Denture (Patient is new to wearing dentures)</label>
            </value>
            <value>
                <fullName>Replacement Denture</fullName>
                <label>Replacement Denture (Patient is a current denture wearer)</label>
            </value>
            <value>
                <fullName>Partial Denture</fullName>
            </value>
            <value>
                <fullName>Implant Supported Denture</fullName>
            </value>
            <value>
                <fullName>All-In-One</fullName>
            </value>
            <value>
                <fullName>Single Tooth Implant</fullName>
            </value>
            <value>
                <fullName>Extraction Only</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Insurance__c.field-meta.xml
<CustomField>
    <fullName>Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Conversation Analyzer Category</description>
    <label>Insurance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Insurance_Plan__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Plan__c</fullName>
    <label>Insurance Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>Ameritas</fullName>
            </value>
            <value>
                <fullName>Blue Cross Blue Shield</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Delta Dental</fullName>
            </value>
            <value>
                <fullName>DentaQuest</fullName>
            </value>
            <value>
                <fullName>Dentemax</fullName>
            </value>
            <value>
                <fullName>GEHA</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Medicaid</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Aetna</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Cigna</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Humana</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - other</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - United Concordia</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - United Healthcare</fullName>
            </value>
            <value>
                <fullName>MetLife</fullName>
            </value>
            <value>
                <fullName>Other Commercial Insurance</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>United Concordia</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__CallTime__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__CallTime__c</fullName>
    <inlineHelpText>Date/Time stamp of Call Start (stored internally as UTC but shown in Salesforce to you in your timezone)</inlineHelpText>
    <label>CallTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__Interaction_Type__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__Interaction_Type__c</fullName>
    <inlineHelpText>The Call or Case type, e.g. Inbound/Outbound/Case</inlineHelpText>
    <label>Interaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Automated Outbound Call</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Internal Call</fullName>
            </value>
            <value>
                <fullName>Phone Callback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__Related_Contact__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__Related_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Contact this call relates to (as indicated by a Task record whose CallObject matches the GUID from this summary)</inlineHelpText>
    <label>Related Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>NVM_Call_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__TaskExists__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__TaskExists__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked if a Salesforce Task exists for this call. ContactWorld injects Tasks for Outbound Calls + Agent answered Inbound ones; support cost to serve analysis. No Task if No Agent involvement</inlineHelpText>
    <label>TaskExists</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Reason_for_Not_Scheduling__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Not_Scheduling__c</fullName>
    <label>Reason for Not Scheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COVID</fullName>
            </value>
            <value>
                <fullName>Date of first available appointment is too far out</fullName>
            </value>
            <value>
                <fullName>Need to arrange transportation</fullName>
            </value>
            <value>
                <fullName>Need to talk to spouse/patient</fullName>
            </value>
            <value>
                <fullName>Practice doesn&apos;t take caller&apos;s insurance</fullName>
            </value>
            <value>
                <fullName>Price shopping</fullName>
            </value>
            <value>
                <fullName>Saving up money/waiting for tax return</fullName>
            </value>
            <value>
                <fullName>Service not offered</fullName>
            </value>
            <value>
                <fullName>Service too expensive</fullName>
            </value>
            <value>
                <fullName>Other [please add note]</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CallSummaryUpdateTest.cls
@istest
public class CallSummaryUpdateTest {
@isTest
    public static void testNVMCallSummary(){
        Integer i;
        List<id> nvm_id = new List<id>();
        
        Account acc = new Account(Name='Test Practice');
        insert acc;
        Contact c = new Contact(FirstName='John',LastName='Test',AccountId=acc.id);
        Insert c;
        List<Task> tlist = new List<Task>();
        List<NVMStatsSF__NVM_Call_Summary__c> nvmlist = new List<NVMStatsSF__NVM_Call_Summary__c>();
        
        /* Task with subcategory*/
        for(i=1 ; i<=496 ; i++){
            Task t = new Task();
            t.WhoId = c.id;
            t.NVM_Call_Result__c = 'Fees/Services';
            t.Answered_Outcome__c = 'New Denture';
            t.Status = 'Completed';
            t.Priority = 'Normal';
            t.Subject = 'Inbound call from ' + i;
            tlist.add(t);
        }
        
        /* Fees/Services Task without subcategory but having 'Reason for not scheduling'*/
        Task t_nosubcategory = new Task();
        t_nosubcategory.WhoId = c.id;
        t_nosubcategory.NVM_Call_Result__c = 'Fees/Services'; 
        t_nosubcategory.Reason_for_Not_Scheduling__c = 'Practice doesn\'t take caller\'s insurance';
        t_nosubcategory.Insurance__c = 'Aetna';
        t_nosubcategory.Status = 'Completed';
        t_nosubcategory.Priority = 'Normal';
        t_nosubcategory.Subject = 'Inbound call from ' + i;
        tlist.add(t_nosubcategory);
        
        /* Task with call result != Fees/Services*/
        Task t_confirmed = new Task();
        t_confirmed.WhoId = c.id;
        t_confirmed.NVM_Call_Result__c = 'Confirmed';      
        t_confirmed.Status = 'Completed';
        t_confirmed.Priority = 'Normal';
        t_confirmed.Subject = 'Inbound call from Confirmed call';
        tlist.add(t_confirmed);         
        
         /* Scheduled Task with subcategory */
        Task t_scheduled = new Task();
        t_scheduled.WhoId = c.id;
        t_scheduled.NVM_Call_Result__c = 'Scheduled'; 
        t_scheduled.Answered_Outcome__c = 'New Denture';
        t_scheduled.Status = 'Completed';
        t_scheduled.Priority = 'Normal';
        t_scheduled.Subject = 'Inbound call from ' + i;
        tlist.add(t_scheduled);
        insert tlist;
        
        /*Create call summaries with tasks having subcategory*/
        for(i=1; i<=498 ; i++){
            NVMStatsSF__NVM_Call_Summary__c nvm = new NVMStatsSF__NVM_Call_Summary__c();
            nvm.NVMStatsSF__Interaction_Type__c = 'Inbound Call';
            nvm.NVMStatsSF__TaskExists__c = true;
            nvm.NVMStatsSF__CallTime__c = Datetime.now();
            nvm.NVMStatsSF__TaskID__c = tlist[i-1].id;
            nvm.NVMStatsSF__CallDisposition__c = 'Fees/Services';
            nvm.NVMStatsSF__Related_Contact__c = c.id;
            nvmlist.add(nvm);            
        }
        
        NVMStatsSF__NVM_Call_Summary__c nvm_scheduled = new NVMStatsSF__NVM_Call_Summary__c();
        nvm_scheduled.NVMStatsSF__Interaction_Type__c = 'Inbound Call';
        nvm_scheduled.NVMStatsSF__TaskExists__c = true;
        nvm_scheduled.NVMStatsSF__CallTime__c = Datetime.now();
        nvm_scheduled.NVMStatsSF__TaskID__c = t_scheduled.id;
        nvm_scheduled.NVMStatsSF__CallDisposition__c = 'Scheduled';
        nvm_scheduled.NVMStatsSF__Related_Contact__c = c.id;
        nvmlist.add(nvm_scheduled); 
        
        insert nvmlist;   
               
        Test.startTest();       
        CallSummaryUpdate nvm = new CallSummaryUpdate(nvmlist);
        Id jobid = Database.executeBatch(nvm,500);
        Test.stopTest();
        
        NVMStatsSF__NVM_Call_Summary__c nvm1 = [Select Id,Call_Result_Subcategory__c from NVMStatsSF__NVM_Call_Summary__c where NVMStatsSF__TaskID__c = :tlist[0].Id limit 1];
        NVMStatsSF__NVM_Call_Summary__c nvm2 = [Select Id,Call_Result_Subcategory__c from NVMStatsSF__NVM_Call_Summary__c where NVMStatsSF__TaskID__c = :t_confirmed.Id limit 1];
        NVMStatsSF__NVM_Call_Summary__c nvm3 = [Select Id,Call_Result_Subcategory__c,Reason_for_not_scheduling__c, Insurance_Plan__c
                                                from NVMStatsSF__NVM_Call_Summary__c where NVMStatsSF__TaskID__c = :t_nosubcategory.Id limit 1];
        NVMStatsSF__NVM_Call_Summary__c nvm4 = [Select Id,Call_Result_Subcategory__c,Reason_for_not_scheduling__c
                                                from NVMStatsSF__NVM_Call_Summary__c where NVMStatsSF__TaskID__c = :t_scheduled.Id limit 1];
        
        System.assertEquals(nvm1.Call_Result_Subcategory__c, tlist[0].Answered_Outcome__c); 
        System.assert(nvm2.Call_Result_Subcategory__c == null);      
        System.assert(nvm3.Call_Result_Subcategory__c == null);  
        System.assertEquals(nvm3.Reason_for_not_scheduling__c, t_nosubcategory.Reason_for_Not_Scheduling__c);
        System.assertEquals(nvm3.Insurance_Plan__c, t_nosubcategory.Insurance__c);
        System.assertEquals(nvm4.Call_Result_Subcategory__c, t_scheduled.Answered_Outcome__c); 
    }
}