force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/NVMStatsSF__NVM_Call_Summary__c.object-meta.xml
<CustomObject>
    <label>Vonage Call Summary</label>
    <nameField>
        <displayFormat>NVMCS-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vonage Call Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Call_Result_Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Call_Result_Subcategory__c</fullName>
    <description>Call Result Subcategory value copied from the Call Task if one was found</description>
    <inlineHelpText>Call Result Subcategory value copied from the Call Task if one was found</inlineHelpText>
    <label>Call Result Subcategory</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Denture</fullName>
                <label>New Denture (Patient is new to wearing dentures)</label>
            </value>
            <value>
                <fullName>Replacement Denture</fullName>
                <label>Replacement Denture (Patient is a current denture wearer)</label>
            </value>
            <value>
                <fullName>Partial Denture</fullName>
            </value>
            <value>
                <fullName>Implant Supported Denture</fullName>
            </value>
            <value>
                <fullName>All-In-One</fullName>
            </value>
            <value>
                <fullName>Single Tooth Implant</fullName>
            </value>
            <value>
                <fullName>Extraction Only</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Insurance_Plan__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Plan__c</fullName>
    <label>Insurance Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aetna</fullName>
            </value>
            <value>
                <fullName>Ameritas</fullName>
            </value>
            <value>
                <fullName>Blue Cross Blue Shield</fullName>
            </value>
            <value>
                <fullName>Cigna</fullName>
            </value>
            <value>
                <fullName>Delta Dental</fullName>
            </value>
            <value>
                <fullName>DentaQuest</fullName>
            </value>
            <value>
                <fullName>Dentemax</fullName>
            </value>
            <value>
                <fullName>GEHA</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Humana</fullName>
            </value>
            <value>
                <fullName>Medicaid</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Aetna</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Cigna</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - Humana</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - other</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - United Concordia</fullName>
            </value>
            <value>
                <fullName>Medicare Advantage - United Healthcare</fullName>
            </value>
            <value>
                <fullName>MetLife</fullName>
            </value>
            <value>
                <fullName>Other Commercial Insurance</fullName>
            </value>
            <value>
                <fullName>Principal</fullName>
            </value>
            <value>
                <fullName>United Concordia</fullName>
            </value>
            <value>
                <fullName>United Healthcare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/NVMStatsSF__TaskExists__c.field-meta.xml
<CustomField>
    <fullName>NVMStatsSF__TaskExists__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checked if a Salesforce Task exists for this call. ContactWorld injects Tasks for Outbound Calls + Agent answered Inbound ones; support cost to serve analysis. No Task if No Agent involvement</inlineHelpText>
    <label>TaskExists</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NVMStatsSF__NVM_Call_Summary__c/fields/Reason_for_Not_Scheduling__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Not_Scheduling__c</fullName>
    <label>Reason for Not Scheduling</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COVID</fullName>
            </value>
            <value>
                <fullName>Date of first available appointment is too far out</fullName>
            </value>
            <value>
                <fullName>Need to arrange transportation</fullName>
            </value>
            <value>
                <fullName>Need to talk to spouse/patient</fullName>
            </value>
            <value>
                <fullName>Practice doesn&apos;t take caller&apos;s insurance</fullName>
            </value>
            <value>
                <fullName>Price shopping</fullName>
            </value>
            <value>
                <fullName>Saving up money/waiting for tax return</fullName>
            </value>
            <value>
                <fullName>Service not offered</fullName>
            </value>
            <value>
                <fullName>Service too expensive</fullName>
            </value>
            <value>
                <fullName>Other [please add note]</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduleCallSummaryUpdate.cls
// System.schedule('Call Summary 1', '0 0 * * * ?', new ScheduleCallSummaryUpdate());
// System.schedule('Call Summary 3', '0 30 * * * ?', new ScheduleCallSummaryUpdate());

global class ScheduleCallSummaryUpdate  implements Schedulable  {
  global void execute(SchedulableContext SC) { 
      List<NVMStatsSF__NVM_Call_Summary__c> lstCS; 
      DateTime dtOneHour = DateTime.now().addMinutes(-60);
      DateTime dt15Min = DateTime.now().addMinutes(-15);
      
      lstCS = [Select Id,Call_Result_Subcategory__c,NVMStatsSF__TaskID__c,Reason_for_Not_Scheduling__c, Insurance_Plan__c from NVMStatsSF__NVM_Call_Summary__c 
               where 
               CreatedDate = TODAY AND
               (NVMStatsSF__CallDisposition__c =: 'Fees/Services'OR
                NVMStatsSF__CallDisposition__c =: 'Scheduled') AND
               NVMStatsSF__TaskExists__c = TRUE AND
               (Call_Result_Subcategory__c = '' OR
               Reason_for_Not_Scheduling__c = '' OR
               Insurance_Plan__c = '') ];
      
      Database.executeBatch(new CallSummaryUpdate(lstCS),100);    
  }
}