force-app/main/default/objects/FB_Lead__c/FB_Lead__c.object-meta.xml
<CustomObject>
    <description>Object that stores fields about a Facebook lead, as captured directly from Facebook.</description>
    <label>Facebook Lead</label>
    <nameField>
        <displayFormat>FB-{0000000000}</displayFormat>
        <label>FB Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facebook Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FB_Lead__c/fields/ArchieBot_Total_Score__c.field-meta.xml
<CustomField>
    <fullName>ArchieBot_Total_Score__c</fullName>
    <label>ArchieBot Total Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>FB_Campaign_Name__c</fullName>
    <defaultValue>&quot;Messenger&quot;</defaultValue>
    <label>FB Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Contact__c.field-meta.xml
<CustomField>
    <fullName>FB_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>FB_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_CreatedTime__c.field-meta.xml
<CustomField>
    <fullName>FB_CreatedTime__c</fullName>
    <label>FB_CreatedTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Current_Treatments__c.field-meta.xml
<CustomField>
    <fullName>FB_Current_Treatments__c</fullName>
    <inlineHelpText>Do you currently use any of the following treatments?</inlineHelpText>
    <label>FB Current Treatments</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Dental_Condition__c.field-meta.xml
<CustomField>
    <fullName>FB_Dental_Condition__c</fullName>
    <label>FB Dental Condition</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Email__c.field-meta.xml
<CustomField>
    <fullName>FB_Email__c</fullName>
    <label>FB Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_First_Name__c.field-meta.xml
<CustomField>
    <fullName>FB_First_Name__c</fullName>
    <label>FB First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Form__c.field-meta.xml
<CustomField>
    <fullName>FB_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facebook Form</label>
    <referenceTo>Facebook_Form__c</referenceTo>
    <relationshipName>FB_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_How_Quickly__c.field-meta.xml
<CustomField>
    <fullName>FB_How_Quickly__c</fullName>
    <inlineHelpText>What timeframe are you seeking to receive treatment from any dental discomfort?</inlineHelpText>
    <label>FB How Quickly</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Insurance_Provider__c.field-meta.xml
<CustomField>
    <fullName>FB_Insurance_Provider__c</fullName>
    <label>FB Insurance Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Interested_In_Financing__c.field-meta.xml
<CustomField>
    <fullName>FB_Interested_In_Financing__c</fullName>
    <label>FB_Interested In Financing</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>FB_Last_Name__c</fullName>
    <label>FB Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Most_Important_Factor__c.field-meta.xml
<CustomField>
    <fullName>FB_Most_Important_Factor__c</fullName>
    <inlineHelpText>What has been holding you back from receiving treatment?</inlineHelpText>
    <label>FB Most Important Factor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Notification_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>FB_Notification_Sent_Date__c</fullName>
    <description>The date a notification was sent to the practice about this lead.</description>
    <inlineHelpText>The date a notification was sent to the practice about this lead.</inlineHelpText>
    <label>FB Notification Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Other_Dentists__c.field-meta.xml
<CustomField>
    <fullName>FB_Other_Dentists__c</fullName>
    <inlineHelpText>Have you received a treatment plan from another dentist recently?</inlineHelpText>
    <label>FB Other Dentists</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Phone__c.field-meta.xml
<CustomField>
    <fullName>FB_Phone__c</fullName>
    <label>FB Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FB_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Using_Insurance__c.field-meta.xml
<CustomField>
    <fullName>FB_Using_Insurance__c</fullName>
    <label>FB Using Insurance</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_What_Service__c.field-meta.xml
<CustomField>
    <fullName>FB_What_Service__c</fullName>
    <label>FB What Service</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Zip__c.field-meta.xml
<CustomField>
    <fullName>FB_Zip__c</fullName>
    <label>FB Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Facebook Leads</relationshipLabel>
    <relationshipName>Facebook_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/SMS1_Notification_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>SMS1_Notification_Sent_Date__c</fullName>
    <label>SMS1 Notification Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/SMS2_Notification_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>SMS2_Notification_Sent_Date__c</fullName>
    <label>SMS2 Notification Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Adibot_Have_Dental_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Adibot_Have_Dental_Insurance__c</fullName>
    <label>Archie Bot Have Dental Insurance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Adibot_How_Soon_Tooth_Replacement__c.field-meta.xml
<CustomField>
    <fullName>Adibot_How_Soon_Tooth_Replacement__c</fullName>
    <label>Archie Bot How Soon Tooth Replacement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Adibot_Interested_Financing_Options__c.field-meta.xml
<CustomField>
    <fullName>Adibot_Interested_Financing_Options__c</fullName>
    <label>Archie Bot Interested Financing Options</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Adibot_Preventing_Seeking_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Adibot_Preventing_Seeking_Treatment__c</fullName>
    <label>Archie Bot Preventing Seeking Treatment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Adibot_Type_Dental_Treatment__c.field-meta.xml
<CustomField>
    <fullName>Adibot_Type_Dental_Treatment__c</fullName>
    <label>Archie Bot Type Dental Treatment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Adibot_What_Dental_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Adibot_What_Dental_Insurance__c</fullName>
    <label>Archie Bot Current Dental Insurance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ArchieBot_Extractions_NDWP__c.field-meta.xml
<CustomField>
    <fullName>ArchieBot_Extractions_NDWP__c</fullName>
    <label>ArchieBot Extractions NDWP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>FB_Campaign_Name__c</fullName>
    <label>FB Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Notify_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Notify_Practice__c</fullName>
    <formula>FB_Practice__r.FB_Notify_Practice__c</formula>
    <label>FB Notify Practice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Practice_Email__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice_Email__c</fullName>
    <formula>IF(FB_Practice__r.FB_Practice_Email__c != &apos;&apos;,
    FB_Practice__r.FB_Practice_Email__c,
    FB_Practice__r.FDA_Email__c 
)</formula>
    <label>FB Practice Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Facebook.recordType-meta.xml
<RecordType>
    <fullName>Facebook</fullName>
    <active>true</active>
    <businessProcess>Standard Process</businessProcess>
    <label>Facebook</label>
</RecordType>

force-app/main/default/classes/FBPracticeNotifier.cls
public class FBPracticeNotifier {
    
    public static void sendSMSNotifications() {
          List<FB_Lead__c> lstSMS = new List<FB_Lead__c>();
          List<FB_Lead__c> lstFBMessenger = [SELECT id,FB_Contact__c,FB_Practice__c, FB_Practice__r.FB_Lead_Optin__c, FB_Practice__r.FDA_Email__c,
                                  FB_Practice__r.FB_Practice_Email__c, FB_Practice__r.FB_Practice_CC_Email__c, FB_Practice__r.Time_Local__c, FB_Practice__r.Location_Id_5_Digit__c,
                                  FB_First_Name__c, FB_Last_Name__c, FB_Email__c, FB_Phone__c, FB_Campaign_Name__c, CreatedDate,
                                  FB_Practice__r.Notify_Practice_Exclusions__c, FB_Dental_Condition__c, FB_Current_Treatments__c,
                                  FB_Most_Important_Factor__c,  FB_Other_Dentists__c, FB_Interested_In_Financing__c,
                                  FB_Form__r.Name, FB_Notification_Sent_Date__c,SMS1_Notification_Sent_Date__c,SMS2_Notification_Sent_Date__c,
                                  ArchieBot_Total_Score__c, Lead__r.Name, Lead__r.Email, Lead__r.Phone, Lead__r.PostalCode,Lead__r.fB_Practice__c,
                                  Lead__r.Adibot_Preventing_Seeking_Treatment__c,Lead__r.Adibot_Type_Dental_Treatment__c,Lead__r.Adibot_Have_Dental_Insurance__c,
                                  Lead__r.Adibot_What_Dental_Insurance__c,Lead__r.Adibot_Interested_Financing_Options__c,Lead__r.Adibot_How_Soon_Tooth_Replacement__c ,
                                  Lead__r.ArchieBot_Extractions_NDWP__c,                                             
                                  FB_Zip__c,FB_How_Quickly__c,FB_Insurance_Provider__c,FB_Using_Insurance__c,FB_What_Service__c
                                  FROM  FB_Lead__c
                                  WHERE Lead__c != null
                                  AND FB_Practice__r.FB_Lead_Optin__c =: TRUE
                                  AND FB_Practice__r.FB_Notify_practice__c =: TRUE 
                                  AND FB_Practice__r.Facebook_SMS1__c != NULL                                      
                                  AND SMS1_Notification_Sent_Date__c = NULL 
                                  AND ArchieBot_Total_Score__c > 5
                                  AND CreatedDate = Last_N_Days: 3
                                  AND Lead__c IN (SELECT LeadId FROM MessagingSession WHERE Status = 'Ended' AND LeadId != null AND MessagingChannel.DeveloperName LIKE 'FACEBOOK%')
                                  LIMIT 5000]; 
        
        List<FB_Lead__c> lstFBForms =  [SELECT id,FB_Contact__c,FB_Practice__c, FB_Practice__r.FB_Lead_Optin__c, FB_Practice__r.FDA_Email__c,
                                  FB_Practice__r.FB_Practice_Email__c, FB_Practice__r.FB_Practice_CC_Email__c, FB_Practice__r.Time_Local__c, FB_Practice__r.Location_Id_5_Digit__c,
                                  FB_First_Name__c, FB_Last_Name__c, FB_Email__c, FB_Phone__c, FB_Campaign_Name__c, CreatedDate,
                                  FB_Practice__r.Notify_Practice_Exclusions__c, FB_Dental_Condition__c, FB_Current_Treatments__c,
                                  FB_Most_Important_Factor__c,  FB_Other_Dentists__c, FB_Interested_In_Financing__c,
                                  FB_Form__r.Name, FB_Notification_Sent_Date__c,SMS1_Notification_Sent_Date__c,SMS2_Notification_Sent_Date__c,
                                  ArchieBot_Total_Score__c, Lead__r.Name, Lead__r.Email, Lead__r.Phone, Lead__r.PostalCode,Lead__r.fB_Practice__c,
                                  Lead__r.Adibot_Preventing_Seeking_Treatment__c,Lead__r.Adibot_Type_Dental_Treatment__c,Lead__r.Adibot_Have_Dental_Insurance__c,
                                  Lead__r.Adibot_What_Dental_Insurance__c,Lead__r.Adibot_Interested_Financing_Options__c,Lead__r.Adibot_How_Soon_Tooth_Replacement__c ,
                                  Lead__r.ArchieBot_Extractions_NDWP__c,                                        
                                  FB_Zip__c,FB_How_Quickly__c,FB_Insurance_Provider__c,FB_Using_Insurance__c,FB_What_Service__c
                                  FROM  FB_Lead__c
                                  WHERE FB_Form__c !=NULL
                                  AND FB_Practice__r.FB_Lead_Optin__c =: TRUE 
                                  AND FB_Practice__r.FB_Notify_practice__c =: TRUE 
                                  AND FB_Practice__r.Facebook_SMS1__c != NULL                                      
                                  AND SMS1_Notification_Sent_Date__c = NULL 
                                  AND FB_CreatedTime__c = Last_N_Days: 3
                                  LIMIT 5000];
        
        lstSMS.addAll(lstFBMessenger);
        lstSMS.addAll(lstFBForms);
        FBLeadSMS.sendFBLeadSMS(lstSMS);
    }
    public static void sendFBFormLeadsNotification() {
        
        List<FB_Lead__c> lstFB = [SELECT id,FB_Contact__c,FB_Practice__c, FB_Practice__r.FB_Lead_Optin__c, FB_Practice__r.FDA_Email__c,
                                  FB_Practice__r.FB_Practice_Email__c, FB_Practice__r.FB_Practice_CC_Email__c, FB_Practice__r.Time_Local__c, 
                                  FB_Practice__r.Location_Id_5_Digit__c,
                                  FB_First_Name__c, FB_Last_Name__c, FB_Email__c, FB_Phone__c, FB_Campaign_Name__c, CreatedDate,
                                  FB_Practice__r.Notify_Practice_Exclusions__c,  FB_Dental_Condition__c, FB_Current_Treatments__c,
                                  FB_Most_Important_Factor__c,  FB_Other_Dentists__c, FB_Interested_In_Financing__c,
                                  FB_Form__r.Name, FB_Notification_Sent_Date__c,SMS1_Notification_Sent_Date__c,SMS2_Notification_Sent_Date__c,
                                  ArchieBot_Total_Score__c, Lead__r.Name, Lead__r.Email, Lead__r.Phone, Lead__r.PostalCode,Lead__r.fB_Practice__c,
                                  Lead__r.Adibot_Preventing_Seeking_Treatment__c,Lead__r.Adibot_Type_Dental_Treatment__c,Lead__r.Adibot_Have_Dental_Insurance__c,
                                  Lead__r.Adibot_What_Dental_Insurance__c,Lead__r.Adibot_Interested_Financing_Options__c,Lead__r.Adibot_How_Soon_Tooth_Replacement__c,
                                   Lead__r.ArchieBot_Extractions_NDWP__c,
                                  FB_Zip__c,FB_How_Quickly__c,FB_Insurance_Provider__c,FB_Using_Insurance__c,FB_What_Service__c
                                  FROM  FB_Lead__c
                                  WHERE FB_Form__c !=NULL
                                  AND FB_Notification_Sent_Date__c = NULL 
                                  AND FB_Practice__r.FB_Lead_Optin__c =: TRUE 
                                  AND FB_Practice__r.FB_Notify_practice__c =: TRUE 
                                  AND FB_CreatedTime__c = Last_N_Days: 3
                                  LIMIT 5000];
         System.debug(lstFB);
        FBLeadEmail.sendFBLeadNotification(lstFB,'Form');
        
    }
    
    public static void sendFBMessengerLeadsNotification() {
        
        List<FB_Lead__c> lstFB = [SELECT id,FB_Contact__c,FB_Practice__c, FB_Practice__r.FB_Lead_Optin__c, FB_Practice__r.FDA_Email__c,
                                  FB_Practice__r.FB_Practice_Email__c, FB_Practice__r.FB_Practice_CC_Email__c, FB_Practice__r.Time_Local__c,FB_Practice__r.Location_Id_5_Digit__c,
                                  FB_First_Name__c, FB_Last_Name__c, FB_Email__c, FB_Phone__c, FB_Campaign_Name__c, CreatedDate,
                                  FB_Practice__r.Notify_Practice_Exclusions__c, FB_Dental_Condition__c, FB_Current_Treatments__c,
                                  FB_Most_Important_Factor__c,  FB_Other_Dentists__c, FB_Interested_In_Financing__c,
                                  FB_Form__r.Name, FB_Notification_Sent_Date__c,SMS1_Notification_Sent_Date__c,SMS2_Notification_Sent_Date__c,
                                  ArchieBot_Total_Score__c, Lead__r.Name, Lead__r.Email, Lead__r.Phone, Lead__r.PostalCode,Lead__r.fB_Practice__c,
                                  Lead__r.Adibot_Preventing_Seeking_Treatment__c,Lead__r.Adibot_Type_Dental_Treatment__c,Lead__r.Adibot_Have_Dental_Insurance__c,
                                  Lead__r.Adibot_What_Dental_Insurance__c,Lead__r.Adibot_Interested_Financing_Options__c,Lead__r.Adibot_How_Soon_Tooth_Replacement__c ,
                                  Lead__r.ArchieBot_Extractions_NDWP__c,
                                  FB_Zip__c,FB_How_Quickly__c,FB_Insurance_Provider__c,FB_Using_Insurance__c,FB_What_Service__c
                                  FROM  FB_Lead__c
                                  WHERE Lead__c != null
                                  AND ArchieBot_Total_Score__c > 5
                                  AND FB_Notification_Sent_Date__c = NULL 
                                  AND FB_Practice__r.FB_Lead_Optin__c =: TRUE
                                  AND FB_Practice__r.FB_Notify_practice__c =: TRUE 
                                  AND CreatedDate = Last_N_Days: 3
                                  AND Lead__c IN (SELECT LeadId FROM MessagingSession WHERE Status = 'Ended' AND LeadId != null AND MessagingChannel.DeveloperName LIKE 'FACEBOOK%')
                                  LIMIT 5000]; 
        
        System.debug('List in FBPracticeNotifier.sendFBMessengerLeadsNotification: ' + lstFB);
        FBLeadEmail.sendFBLeadNotification(lstFB,'Messenger');
    }
    
    
}