force-app/main/default/objects/FB_Lead__c/FB_Lead__c.object-meta.xml
<CustomObject>
    <description>Object that stores fields about a Facebook lead, as captured directly from Facebook.</description>
    <label>Facebook Lead</label>
    <nameField>
        <displayFormat>FB-{0000000000}</displayFormat>
        <label>FB Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facebook Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FB_Lead__c/fields/FB_1st_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_1st_Contact_Time__c</fullName>
    <description>1st time the lead was contacted.</description>
    <label>FB 1st Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_2nd_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_2nd_Contact_Time__c</fullName>
    <description>2nd time the lead was contacted</description>
    <label>FB 2nd Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_3rd_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_3rd_Contact_Time__c</fullName>
    <description>3rd time the lead was contacted.</description>
    <label>FB 3rd Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Message_Id__c.field-meta.xml
<CustomField>
    <fullName>FB_Message_Id__c</fullName>
    <description>Id of the message to be sent, based on scheduled contact 1,2,or 3</description>
    <formula>IF(  FB_Scheduled_1__c   == TODAY() , 1,
IF(  FB_Scheduled_2__c  == TODAY(), 2,
IF(  FB_Scheduled_3__c  == TODAY(), 3,
0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FB Message Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FB_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Practice_Id__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice_Id__c</fullName>
    <label>FB Practice Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Facebook Leads</relationshipLabel>
    <relationshipName>Facebook_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Scheduled__c</fullName>
    <formula>If(First_Appointment_Id__c != null,1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheduled</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_1st_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_1st_Contact_Time__c</fullName>
    <label>FB 1st Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_2nd_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_2nd_Contact_Time__c</fullName>
    <label>FB 2nd Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_3rd_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_3rd_Contact_Time__c</fullName>
    <label>FB 3rd Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Message_Id__c.field-meta.xml
<CustomField>
    <fullName>FB_Message_Id__c</fullName>
    <formula>IF( FB_Scheduled_1__c == TODAY() , 1,
IF( FB_Scheduled_2__c == TODAY(), 2,
IF( FB_Scheduled_3__c == TODAY(), 3,
0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FB Message Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Practice_Id__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice_Id__c</fullName>
    <label>FB Practice Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchFBMessengerEmail.cls
public class BatchFBMessengerEmail implements Database.Batchable<sObject> {
    
    public static Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT id,FB_Message_Id__c,Lead__c,Lead__r.Email,FB_Practice__c, FB_Practice__r.FB_Lead_Optin__c, ' +
            'FB_Practice__r.FB_Discount_Optin__c, FB_Practice_Id__c FROM FB_Lead__c ' +
            'WHERE Lead__c !=NULL AND ' +
            'Scheduled__c = 0 AND ' +
            '( (FB_Message_Id__c = 1 AND FB_1st_Contact_Time__c = NULL) OR ' +
            '(FB_Message_Id__c = 2 AND FB_2nd_Contact_Time__c = NULL) OR ' +
            '(FB_Message_Id__c = 3 AND FB_3rd_Contact_Time__c = NULL))';
        
        return Database.getQueryLocator(query);	
    }
    
    public static void execute(Database.BatchableContext bc, List<FB_Lead__c> lstFB){
        OrgWideEmailAddress owa; 
        List<Messaging.SingleEmailMessage> allmsg= new List<Messaging.SingleEmailMessage>();  
        List<String> toAddr;        
        List<EmailTemplate> lstTemplatesCoupon;
        List<EmailTemplate> lstTemplatesNoCoupon;
        List<EmailTemplate> lstTemplatesNoLocation;
        Set<string> templateCoupon = new Set<String> {'FB1','FB2','FB3'};
        Set<string> templatesNoCoupon = new Set<String> {'FB1','FB2NoCoupon','FB3NoCoupon'};
        Set<string> templatesNoLocation = new Set<String> {'FB1NoLocation','FB2NoLocation','FB3NoLocation'};                    
        Messaging.SingleEmailMessage mail;        
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'patientsupport@affordablecare.com'];        
        lstTemplatesCoupon = [Select id,name from EmailTemplate where name in: templateCoupon ORDER BY name];       
        lstTemplatesNoCoupon = [Select id,name from EmailTemplate where name in: templatesNoCoupon ORDER BY name];
        lstTemplatesNoLocation = [Select id,name from EmailTemplate where name in: templatesNoLocation ORDER BY name];
        
        for(FB_Lead__c fb:lstFB) {
            //instantiate mail, assign template based on message id
            Integer x = (Integer)fb.FB_Message_Id__c;
            mail = new Messaging.SingleEmailMessage();
            toAddr = new List<String>(); 
            toAddr.add(fb.Lead__c);
            mail.optoutpolicy='FILTER';
            mail.setUseSignature(false);
            if ( owea.size() > 0 ) {
                mail.setOrgWideEmailAddressId(owea.get(0).Id);
            }
            mail.setBCCSender(false);
            mail.toaddresses = toaddr;
            mail.setWhatId(fb.id);
            mail.setTargetObjectId(fb.Lead__c);   
            
            //set template based on whether the practice exists and offers coupons  
            if(fb.FB_Practice__c == null)
                mail.setTemplateId(lstTemplatesNoLocation.get(x-1).id);          
            else if(fb.FB_Practice__r.FB_Discount_Optin__c)
                mail.setTemplateId(lstTemplatesCoupon.get(x-1).id);  
            else
                mail.setTemplateId(lstTemplatesNoCoupon.get(x-1).id);      
            
            allmsg.add(mail);   
        
            //assign timestamp to track mail send
            if(x==1)
                fb.FB_1st_Contact_Time__c = Date.today();
            else if (x==2) 
                fb.FB_2nd_Contact_Time__c = Date.today();
            else if (x==3) 
                fb.FB_3rd_Contact_Time__c = Date.today();
        }
        
        //send emails
        Messaging.sendEmail(allmsg,false);
        
        //timestamp tracking objects
        update lstFb;  
        
    }
    
    public static void finish(Database.BatchableContext bc){
    }
    
}