force-app/main/default/objects/FB_Lead__c/FB_Lead__c.object-meta.xml
<CustomObject>
    <description>Object that stores fields about a Facebook lead, as captured directly from Facebook.</description>
    <label>Facebook Lead</label>
    <nameField>
        <displayFormat>FB-{0000000000}</displayFormat>
        <label>FB Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facebook Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FB_Lead__c/fields/FB_1st_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_1st_Contact_Time__c</fullName>
    <description>1st time the lead was contacted.</description>
    <label>FB 1st Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_2nd_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_2nd_Contact_Time__c</fullName>
    <description>2nd time the lead was contacted</description>
    <label>FB 2nd Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_3rd_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_3rd_Contact_Time__c</fullName>
    <description>3rd time the lead was contacted.</description>
    <label>FB 3rd Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Message_Id__c.field-meta.xml
<CustomField>
    <fullName>FB_Message_Id__c</fullName>
    <description>Id of the message to be sent, based on scheduled contact 1,2,or 3</description>
    <formula>IF(  FB_Scheduled_1__c   == TODAY() , 1,
IF(  FB_Scheduled_2__c  == TODAY(), 2,
IF(  FB_Scheduled_3__c  == TODAY(), 3,
0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FB Message Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FB_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Scheduled_1__c.field-meta.xml
<CustomField>
    <fullName>FB_Scheduled_1__c</fullName>
    <description>1st date lead is scheduled to be contacted</description>
    <label>FB Scheduled 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Scheduled_2__c.field-meta.xml
<CustomField>
    <fullName>FB_Scheduled_2__c</fullName>
    <description>2nd date lead is scheduled for contact</description>
    <label>FB Scheduled 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Facebook Leads</relationshipLabel>
    <relationshipName>Facebook_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_1st_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_1st_Contact_Time__c</fullName>
    <label>FB 1st Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_2nd_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_2nd_Contact_Time__c</fullName>
    <label>FB 2nd Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_3rd_Contact_Time__c.field-meta.xml
<CustomField>
    <fullName>FB_3rd_Contact_Time__c</fullName>
    <label>FB 3rd Contact Time</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Message_Id__c.field-meta.xml
<CustomField>
    <fullName>FB_Message_Id__c</fullName>
    <formula>IF( FB_Scheduled_1__c == TODAY() , 1,
IF( FB_Scheduled_2__c == TODAY(), 2,
IF( FB_Scheduled_3__c == TODAY(), 3,
0)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FB Message Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Notify_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Notify_Practice__c</fullName>
    <formula>FB_Practice__r.FB_Notify_Practice__c</formula>
    <label>FB Notify Practice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Scheduled_1__c.field-meta.xml
<CustomField>
    <fullName>FB_Scheduled_1__c</fullName>
    <description>1st date lead is scheduled to be contacted</description>
    <label>FB Scheduled 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Scheduled_2__c.field-meta.xml
<CustomField>
    <fullName>FB_Scheduled_2__c</fullName>
    <description>2nd date lead is scheduled for contact</description>
    <label>FB Scheduled 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <description>Temp - importing practice owners</description>
    <label>Location Id</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchFBMessengerEmailTest.cls
@isTest
public class BatchFBMessengerEmailTest {
    
    @isTest
    static void runTest()
    {
        
        FB_Lead__c fb, fb2;
        Account a,a2;
        Lead l,l2;   
        List<FB_Lead__c> lstFB;
        
        a = new Account(name='Charlotte - North Carolina',Location_Id__c = '01002',
                        FB_Lead_Optin__c=true,FB_Discount_Optin__c=true,FB_LocalMed__c='test.com',FB_Notify_practice__c=true,FB_Email_campaign_opt_in__c=true);                               
        insert a;
        
        
        l = new Lead(firstname='John',lastname='Doe',email='jdoe@example.com',company='Charlotte - North Carolina');
        l.FB_Practice__c = a.id;
        insert l;  
        
        l2 = new Lead(firstname='Jane',lastname='Doe',email='janedoe@example.com',company='test');
        l2.FB_Practice__c = null;
        insert l2;  
        
        fb = new FB_Lead__c();
        fb.FB_Practice__c = a.id;
        fb.Lead__c = l.id; 
        fb.FB_Scheduled_1__c = Date.today();  
        insert fb;
        
        fb2 = new FB_Lead__c();
        fb2.FB_Practice__c = null;
        fb2.Lead__c = l2.id; 
        fb2.FB_Scheduled_2__c = Date.today();
        insert fb2;
        
        Test.StartTest();          
        Id batchJobId = Database.executeBatch(new BatchFBMessengerEmail(), 10);  
        Test.stopTest();
        
        lstFB = [SELECT Id, Lead__c,FB_Message_Id__c,FB_1st_Contact_Time__c,
                 FB_2nd_Contact_Time__c, FB_3rd_Contact_Time__c
                 FROM FB_Lead__c 
                 ORDER BY CreatedDate]; 
        
        for(FB_Lead__c f:lstFB) {
            system.debug(f);
        }
        
        System.assertEquals(Date.today(), lstFB[0].FB_1st_Contact_Time__c);
        System.assertEquals(Date.today(), lstFB[1].FB_2nd_Contact_Time__c);
        
    }
    
}