force-app/main/default/objects/FB_Lead__c/FB_Lead__c.object-meta.xml
<CustomObject>
    <description>Object that stores fields about a Facebook lead, as captured directly from Facebook.</description>
    <label>Facebook Lead</label>
    <nameField>
        <displayFormat>FB-{0000000000}</displayFormat>
        <label>FB Lead Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facebook Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FB_Lead__c/fields/ArchieBot_Total_Score__c.field-meta.xml
<CustomField>
    <fullName>ArchieBot_Total_Score__c</fullName>
    <label>ArchieBot Total Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>FB_Campaign_Name__c</fullName>
    <defaultValue>&quot;Messenger&quot;</defaultValue>
    <label>FB Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Contact__c.field-meta.xml
<CustomField>
    <fullName>FB_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>FB_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Current_Treatments__c.field-meta.xml
<CustomField>
    <fullName>FB_Current_Treatments__c</fullName>
    <inlineHelpText>Do you currently use any of the following treatments?</inlineHelpText>
    <label>FB Current Treatments</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Dental_Condition__c.field-meta.xml
<CustomField>
    <fullName>FB_Dental_Condition__c</fullName>
    <label>FB Dental Condition</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Email__c.field-meta.xml
<CustomField>
    <fullName>FB_Email__c</fullName>
    <label>FB Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_First_Name__c.field-meta.xml
<CustomField>
    <fullName>FB_First_Name__c</fullName>
    <label>FB First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Form__c.field-meta.xml
<CustomField>
    <fullName>FB_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facebook Form</label>
    <referenceTo>Facebook_Form__c</referenceTo>
    <relationshipName>FB_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Form_Id__c.field-meta.xml
<CustomField>
    <fullName>FB_Form_Id__c</fullName>
    <label>FB Form Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_How_Quickly__c.field-meta.xml
<CustomField>
    <fullName>FB_How_Quickly__c</fullName>
    <inlineHelpText>What timeframe are you seeking to receive treatment from any dental discomfort?</inlineHelpText>
    <label>FB How Quickly</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Interested_In_Financing__c.field-meta.xml
<CustomField>
    <fullName>FB_Interested_In_Financing__c</fullName>
    <label>FB_Interested In Financing</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>FB_Last_Name__c</fullName>
    <label>FB Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Most_Important_Factor__c.field-meta.xml
<CustomField>
    <fullName>FB_Most_Important_Factor__c</fullName>
    <inlineHelpText>What has been holding you back from receiving treatment?</inlineHelpText>
    <label>FB Most Important Factor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Notification_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>FB_Notification_Sent_Date__c</fullName>
    <description>The date a notification was sent to the practice about this lead.</description>
    <inlineHelpText>The date a notification was sent to the practice about this lead.</inlineHelpText>
    <label>FB Notification Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Other_Dentists__c.field-meta.xml
<CustomField>
    <fullName>FB_Other_Dentists__c</fullName>
    <inlineHelpText>Have you received a treatment plan from another dentist recently?</inlineHelpText>
    <label>FB Other Dentists</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Phone__c.field-meta.xml
<CustomField>
    <fullName>FB_Phone__c</fullName>
    <label>FB Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>FB_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/FB_Zip__c.field-meta.xml
<CustomField>
    <fullName>FB_Zip__c</fullName>
    <label>FB Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Facebook Leads</relationshipLabel>
    <relationshipName>Facebook_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/SMS1_Notification_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>SMS1_Notification_Sent_Date__c</fullName>
    <label>SMS1 Notification Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FB_Lead__c/fields/SMS2_Notification_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>SMS2_Notification_Sent_Date__c</fullName>
    <label>SMS2 Notification Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>FB_Campaign_Name__c</fullName>
    <label>FB Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Form_Id__c.field-meta.xml
<CustomField>
    <fullName>FB_Form_Id__c</fullName>
    <label>FB Form Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Notify_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Notify_Practice__c</fullName>
    <formula>FB_Practice__r.FB_Notify_Practice__c</formula>
    <label>FB Notify Practice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Practice__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FB Practice</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FB_Practice_Email__c.field-meta.xml
<CustomField>
    <fullName>FB_Practice_Email__c</fullName>
    <formula>IF(FB_Practice__r.FB_Practice_Email__c != &apos;&apos;,
    FB_Practice__r.FB_Practice_Email__c,
    FB_Practice__r.FDA_Email__c 
)</formula>
    <label>FB Practice Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FBPracticeNotifierTest.cls
@isTest
private class FBPracticeNotifierTest {
    
    static testMethod void runTest() {
        // Create test data 
        List<Account> lstacc = new List<Account>();
        List<FB_Lead__c> lstLeads = new List<FB_Lead__c>();
        
        
        Lead l = new Lead (FirstName='John',LastName='Doe',Email='jd@example.com',Company='Test');
        insert l;
        
        Account a1 = new Account(Name = 'Hot Springs - Arkansas',
                                 FB_Lead_Optin__c = true,
                                 FB_Notify_Practice__c = true,
                                 FB_Email_Campaign_Opt_In__c = true,
                                 Facebook_SMS1__c = '9191115555',
                                 Time_UTCOffset__c = -18000,
                                 Time_DSTOffset__c = 0);
        lstacc.add(a1);
        Account a2 = new Account(Name = 'York - Pennsylvania',
                                 FB_Lead_Optin__c = true,
                                 FB_Notify_Practice__c = true,
                                 FB_Email_Campaign_Opt_In__c = true,
                                 Facebook_SMS1__c = '9191116666',
                                 Facebook_SMS2__c = '9191117777',
                                 Time_UTCOffset__c = -18000,
                                 Time_DSTOffset__c = 0);
        lstacc.add(a2);
        insert lstacc; 
   
        Contact c1 = new Contact(FirstName = 'FDA', LastName = '09999', 
                                 AccountId = a1.Id,email = 'fda09999@affordabledentures.com',
                                 MobilePhone = '9191115555');
        insert c1;
        
        Contact c2 = new Contact(FirstName = 'FDA', LastName = '09998', 
                                 AccountId = a2.Id,email = 'fda09998@affordabledentures.com',
                                 MobilePhone = '9192225555');
        insert c2; 
        
        for(Integer i = 0; i<=1; i++){         
                FB_Lead__c lead = new FB_Lead__c();
            	lead.Lead__c = l.id;
                lead.FB_Practice__c = lstacc[i].id;
                lead.FB_First_Name__c = 'Test ' + i ;
                lead.FB_Last_Name__c = 'Lead ' + i;
                lead.FB_Email__c = 'Test' + i  + '.Lead' + i  + '@example.com';
                 lead.ArchieBot_Total_Score__c = 25;
                 lead.FB_Notification_Sent_Date__c = null;
                System.debug(lead);
                lstLeads.add(lead);
        }       		
        insert lstLeads;
        
        Test.startTest();
        
        // Call the method to test
        FBPracticeNotifier.sendFBFormLeadsNotification();
        FBPracticeNotifier.sendFBMessengerLeadsNotification();
        FBPracticeNotifier.sendSMSNotifications();
        Test.stopTest();
        
        // Add assertions here
        List<FB_Lead__c> lstFB = [SELECT id,Lead__c, FB_Form_Id__c,FB_Notification_Sent_Date__c,FB_Contact__c,FB_Practice__c, FB_Practice__r.FB_Lead_Optin__c, FB_Practice__r.FDA_Email__c,
                                  FB_Practice__r.FB_Practice_Email__c, FB_Practice__r.FB_Practice_CC_Email__c, FB_Practice__r.Time_Local__c,
                                  FB_First_Name__c, FB_Last_Name__c, FB_Email__c, FB_Phone__c, FB_Campaign_Name__c, CreatedDate,
                                  FB_Practice__r.Notify_Practice_Exclusions__c, FB_Zip__c, FB_Dental_Condition__c, FB_Current_Treatments__c,
                                  FB_How_Quickly__c, FB_Most_Important_Factor__c,  FB_Other_Dentists__c, FB_Interested_In_Financing__c,
                                  FB_Form__r.Name,SMS1_Notification_Sent_Date__c,SMS2_Notification_Sent_Date__c
                                  FROM  FB_Lead__c]; 
        
        for(FB_Lead__c lead: lstFB) {
            System.debug(lead);
        }
    
    }
}